### ISSUE TITLE
Trace verification still fails 

### ISSUE THREAD

**Issue by gamarin2** [EmerisHQ/demeris-api-server#27]
See https://api.emeris.com/v1/account/d214c44aba0331c0f76e53ec80cbddc051fde22f/balance

This was supposed to have been fixed here https://github.com/allinbits/demeris-backend/pull/222, but apparently it's still happening

**Comment by gsora** [comment]
Just checked on the branch which we're running on prod, that PR's code is present.

At this point I'm not sure if we're encountering a different bug in that code flow.

**Comment by gsora** [comment]
Pretty sure what we're seeing here is due to `/balance` and `/verify_trace` not going through the same handler code.

The PR mentioned here only accounts for `/verify_trace`, we should back port the same fix on `/balance` too.
