### ISSUE TITLE
don't return 400 error codes

### ISSUE THREAD

**Issue by akc2267** [EmerisHQ/demeris-api-server#66]
this is a ticket for the PR to fix the reopened #220:  https://app.zenhub.com/workspaces/emeris-back-end-619cd009cc778000112d6259/issues/allinbits/demeris-backend/220

**Comment by gsora** [comment]
I'm not sure I follow? `verify_trace` returns non-200 codes ONLY when there's a fatal error, like the database not responding or other.

Moving everything to 200 means breaking the meaning of the HTTP status code itself, can't the frontend handle non-200 codes?

**Comment by akc2267** [comment]
the frontend should definitely be capable of handling non-200 error codes. The request to do this on the backend was because this bug was reported late Friday when only Brian and I were available during working hours. There is an epic on the frontend to gracefully handle failures https://app.zenhub.com/workspaces/emeris-front-end-61a8a3c678a51100170b686f/issues/allinbits/demeris/1151

**Comment by gsora** [comment]
I see.

The way I see it, we either add complexity (and misuse of primitives, IMO) to the backend, or we could wait for the frontend to handle errors correctly - I woud push for alternative 2 to be honest.

@sgerogia wdyt?

**Comment by sgerogia** [comment]
Closing as the other ticket was closed also
